"""initial models

Revision ID: ea2004160ed0
Revises: 
Create Date: 2022-10-22 06:20:39.153014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea2004160ed0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_id'), 'group', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('mobile', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile', name='unique_ids_user_mobile')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('expense',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('paid_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('group_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_group_id'), 'expense', ['group_id'], unique=False)
    op.create_index(op.f('ix_expense_id'), 'expense', ['id'], unique=False)
    op.create_index(op.f('ix_expense_paid_by'), 'expense', ['paid_by'], unique=False)
    op.create_table('user_group_mapping',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('group_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_index(op.f('ix_user_group_mapping_group_id'), 'user_group_mapping', ['group_id'], unique=False)
    op.create_index(op.f('ix_user_group_mapping_user_id'), 'user_group_mapping', ['user_id'], unique=False)
    op.create_table('expense_user_mapping',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('expense_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'expense_id')
    )
    op.create_index(op.f('ix_expense_user_mapping_expense_id'), 'expense_user_mapping', ['expense_id'], unique=False)
    op.create_index(op.f('ix_expense_user_mapping_user_id'), 'expense_user_mapping', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expense_user_mapping_user_id'), table_name='expense_user_mapping')
    op.drop_index(op.f('ix_expense_user_mapping_expense_id'), table_name='expense_user_mapping')
    op.drop_table('expense_user_mapping')
    op.drop_index(op.f('ix_user_group_mapping_user_id'), table_name='user_group_mapping')
    op.drop_index(op.f('ix_user_group_mapping_group_id'), table_name='user_group_mapping')
    op.drop_table('user_group_mapping')
    op.drop_index(op.f('ix_expense_paid_by'), table_name='expense')
    op.drop_index(op.f('ix_expense_id'), table_name='expense')
    op.drop_index(op.f('ix_expense_group_id'), table_name='expense')
    op.drop_table('expense')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_group_id'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
